[package]
name = "mersenne-pkc"
version = "0.1.0"
authors = ["thenaesh"]
edition = "2018"

[lib]
name = "mersennepkc"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"
doc = false

[dependencies]
num = "0.2.0"
rand = "0.6.4"
